.TH WAYPROMPT-SSH-ASKPASS 1 2024-03-19 "git.sr.ht/~leon_plickat/wayprompt" "General Commands Manual"
.
.SH NAME
.P
wayprompt-ssh-askpass \- Wayland-native ssh-askpass implementation
.
.
.SH SYNOPSIS
.SY wayprompt\-ssh\-askpass
.YS
.
.
.SH DESCRIPTION
.P
The wayprompt-ssh-askpass executable described in this manual page represents
the ssh-askpass implementation based on wayprompt.
For general information on wayprompt, read
.BR wayprompt (1).
.
.
.SH USE WITH SSH
.P
To use wayprompt-ssh-askpass  as the askpass program for
.BR ssh (1)
as well as for programs that wrap it, like
.BR git (1)
or 
.BR rsync (1),
you need to set and export the \fBSSH_ASKPASS\fR env var to the path to the
wayprompt-ssh-askpass executable.
.
.P
By default, ssh will only use the configured askpass program if it is not
attached to a terminal.
To force ssh to always use the askpass program, set and export
\fBSSH_ASKPASS_REQUIRE=force\fR.
.
.
.SH RETURN VALUE
.P
wayprompt-ssh-askpass will exit with one of the following commands.
.
.TS
tab(@), left, box;
c | c
rB | l.
\fBValue\fR@\fBExplanation\fR
_
0@User triggered "ok" (either by pressing Enter or by clicking the button).
_
1@User triggered "cancel" (either by pressing Escape or by clicking the button) or an error occured.
.TE
.
.
.SH AUTHOR
.P
.MT leonhenrik.plickat@stud.uni-goettingen.de
Leon Henrik Plickat
.ME
.
.
.SH SEE ALSO
.BR wayprompt (1),
.BR wayprompt (5),
.BR ssh (1),
